# -*- coding: utf-8 -*-
"""ML_task-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kjUo0e8aEiAjjKiK0ER3u60Ulu_z1O7T
"""

import pandas as pd

data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/train.csv")
data

#data=data.drop(data[data.Type=='0'].index)
#data

data.isnull()

data.isnull().sum()

"""so we can see now that the columns whose values are more than '0' have null values in them,hance those are:"age,cabin,embarked"
"""

data['Embarked'].value_counts().idxmax()
data

data.fillna({
    'Embarked':'S'
})
data